[package]
name = "maedic"
version = "0.3.0"
edition = "2024"


[lib]
path = "src/lib.rs"

[[bin]]
path= "src/main.rs"
name = "maedic"

[dependencies]
anyhow = "1.0.100"
axum = {version = "0.8.8", features = ["tokio", "macros", "json"]}
bb8 = "0.9.1"
bb8-tiberius = "0.16.0"
config = {version = "0.15.19", features = ["yaml"]}
rstest = "0.26.1"
secrecy = {version = "0.10.3", features = ["serde"]}
serde = "1.0.228"
serde-aux = "4.7.0"
sysinfo = "0.37.2"
thiserror = "2.0.17"
tiberius = {version = "0.12.3", features = ["rustls"], default-features = false}
tokio = {version = "1.49.0", features = ["rt-multi-thread", "macros"]}
tokio-util = { version = "0.7.18", features = ["compat"]}
tracing = "0.1.44"
tracing-subscriber = {version = "0.3.22", features = ["json", "std"]}
